-- GENERATED by scripts/world/bundle.py; edit plugins/fx/fortress/*.lua.
local Sim = (function()
-- Pure, bounded event simulation. No renderer, host time, I/O, or shared RNG.
local Sim = {}
Sim.__index = Sim
Sim.VERSION = 2
Sim.CAPS = { dwarves=12, rooms=48, items=96, jobs=32, incidents=8, artifacts=16, legends=128, announcements=16 }
local KINDS = {"exec", "edit", "read", "web", "task", "mcp", "other"}
local SKILLS = {"plan", "exec", "edit", "read", "trade", "craft"}
local COUNTERS = {"prompts", "tools", "errors", "compactions", "waits", "subagents", "subagents_peak"}
local NEEDS = {"rest", "craft", "knowledge", "fellowship"}
local PREFIX = {"Ember", "Moss", "Copper", "Slate", "Quiet", "Silver", "Amber", "River"}
local SUFFIX = {"hold", "deep", "gate", "hall", "reach", "haven"}
local FIRST = {"Ari", "Bera", "Corin", "Dena", "Evan", "Fenn", "Galen", "Hali"}
local LAST = {"Copperhand", "Mosskeeper", "Slatewright", "Riverward", "Ashweaver", "Brightpick"}
local function num(v) return math.max(0, math.floor(tonumber(v) or 0)) end
local function clone(v)
  if type(v) ~= "table" then return v end
  local o = {}; for k,x in pairs(v) do o[k] = clone(x) end; return o
end
function Sim.hash(text)
  local h = 5381
  text = tostring(text)
  for i=1,#text do h = (h * 33 + text:byte(i)) % 2147483647 end
  return h
end
function Sim.roll(seed, seq, tag, n)
  return Sim.hash(tostring(seed)..":"..tostring(seq)..":"..tag) % n + 1
end
function Sim.safe(word, fallback)
  if type(word) ~= "string" or #word < 4 or #word > 16 or not word:match("^[a-z]+$") then return fallback or "craft" end
  for _,bad in ipairs({"secret", "password", "token", "apikey", "bearer", "credential"}) do
    if word:find(bad, 1, true) then return fallback or "craft" end
  end
  return word
end
function Sim.digest(c)
  local parts = {}
  for _,k in ipairs(COUNTERS) do parts[#parts+1] = tostring(num(c[k])) end
  for _,k in ipairs(KINDS) do parts[#parts+1] = tostring(num((c.tool_kinds or {})[k])) end
  return table.concat(parts, ":")
end
function Sim.canonical(v)
  if type(v) ~= "table" then return type(v)..":"..tostring(v) end
  local keys, out = {}, {}
  for k in pairs(v) do keys[#keys+1] = k end
  table.sort(keys, function(a,b) return tostring(a)<tostring(b) end)
  for _,k in ipairs(keys) do out[#out+1] = tostring(k).."="..Sim.canonical(v[k]) end
  return "{"..table.concat(out,";").."}"
end
function Sim:hash_state() return Sim.hash(Sim.canonical(self:snapshot())) end
function Sim:title(xp)
  local title = "Novice"
  for _,v in ipairs({{5,"Adequate"},{20,"Skilled"},{80,"Expert"},{320,"Legendary"}}) do
    if xp >= v[1] then title = v[2] end
  end
  return title
end
function Sim:id() self.next_id=self.next_id+1; return self.next_id end
function Sim:legend(kind, text, ref, priority)
  local e = {id=self:id(), seq=self.seq, tick=self.clock, year=self.year, kind=kind,
    text=text, ref=ref or 0, priority=priority or 1}
  self.legends[#self.legends+1]=e
  if #self.legends > Sim.CAPS.legends then
    local old=table.remove(self.legends,1)
    self.summary[old.kind]=(self.summary[old.kind] or 0)+1
    self.evicted=self.evicted+1
    self.evicted_through=old.id
  end
  if e.priority>1 or self.clock-self.last_announcement>=80 then
    if e.priority<=1 then self.last_announcement=self.clock end
    if not self.announcement or e.priority>self.announcement.priority then
      self.announcement=clone(e); self.announcement_until=self.clock+16
    else
      self.announcements[#self.announcements+1]=clone(e)
      table.sort(self.announcements,function(a,b)
        if a.priority~=b.priority then return a.priority>b.priority end
        return a.id<b.id
      end)
      if #self.announcements>Sim.CAPS.announcements then table.remove(self.announcements) end
    end
  end
  return e.id
end
function Sim:dwarf(role)
  local id=self:id()
  local skills,needs={},{}
  for _,k in ipairs(SKILLS) do skills[k]=0 end
  for _,k in ipairs(NEEDS) do needs[k]=0 end
  local d={id=id, name=FIRST[Sim.roll(self.seed,id,"first",#FIRST)].." "..LAST[Sim.roll(self.seed,id,"last",#LAST)],
    role=role, skills=skills, needs=needs, mood="content", home=1, job=0}
  self.dwarves[#self.dwarves+1]=d
  return d
end
function Sim:room(kind)
  if #self.rooms >= Sim.CAPS.rooms then return self.rooms[#self.rooms] end
  local r={id=self:id(), kind=kind, z=self.z, level=1, theme="stone", engraving=""}
  self.rooms[#self.rooms+1]=r
  return r
end
function Sim.new(seed, identity)
  local s=setmetatable({schema_version=Sim.VERSION, seed=seed, identity=identity or tostring(seed),
    seq=0, clock=0, next_id=0, year=1, z=0, stress=0, wealth=0, quarry=0,
    profile="classic", subject="craft", material="stone", crew=0, store=0,
    dwarves={}, rooms={}, items={}, jobs={}, incidents={}, artifacts={}, legends={}, summary={},
    announcements={}, announcement=false, announcement_until=0, last_announcement=-80,
    evicted=0, evicted_through=0, failures={}, cooldown=0, last_artifact=-6000,
    counts={prompts=0,tools=0,errors=0,compactions=0,waits=0,subagents=0,subagents_peak=0,tool_kinds={}},
    mood_arc=false, cave_until=0, gap_to=0, last_routine=-80},Sim)
  for _,k in ipairs(KINDS) do s.counts.tool_kinds[k]=0 end
  s.name=PREFIX[Sim.roll(seed,0,"fortress-prefix",#PREFIX)]..SUFFIX[Sim.roll(seed,0,"fortress-suffix",#SUFFIX)]
  s:dwarf("founder"); s:room("plan"); s:room("workshop"); s:room("rest")
  return s
end
function Sim:snapshot()
  local o={}; for k,v in pairs(self) do o[k]=clone(v) end; return o
end
function Sim.restore(data, identity)
  if type(data)~="table" or data.schema_version~=Sim.VERSION or data.identity~=identity then return nil end
  local function finite(v) return type(v)=="number" and v==v and v>=0 and v<9007199254740991 end
  for _,k in ipairs({"seed","clock","seq","next_id","year","z","stress","wealth","quarry","crew","store","evicted","evicted_through","cooldown","cave_until","gap_to"}) do
    if not finite(data[k]) then return nil end
  end
  if type(data.name)~="string" or #data.name>24 or not data.name:match("^[A-Za-z][A-Za-z -]+$") then return nil end
  if type(data.counts)~="table" or type(data.counts.tool_kinds)~="table" or type(data.summary)~="table" or type(data.failures)~="table" or #data.failures>6 then return nil end
  for _,k in ipairs(COUNTERS) do if not finite(data.counts[k]) then return nil end end
  for _,k in ipairs(KINDS) do if not finite(data.counts.tool_kinds[k]) then return nil end end
  for k,cap in pairs(Sim.CAPS) do if type(data[k])~="table" or #data[k]>cap then return nil end end
  if #data.dwarves<1 or #data.rooms<1 then return nil end
  if data.announcement~=false and (type(data.announcement)~="table" or not finite(data.announcement.priority) or type(data.announcement.text)~="string" or not finite(data.announcement_until) or data.announcement_until<data.clock) then return nil end
  if type(data.last_announcement)~="number" then return nil end
  for _,d in ipairs(data.dwarves) do
    if type(d)~="table" or not finite(d.id) or type(d.name)~="string" or not finite(d.job) or type(d.skills)~="table" or type(d.needs)~="table" then return nil end
    for _,k in ipairs(SKILLS) do if not finite(d.skills[k]) then return nil end end
    for _,k in ipairs(NEEDS) do if not finite(d.needs[k]) then return nil end end
  end
  for _,r in ipairs(data.rooms) do
    if type(r)~="table" or not finite(r.id) or type(r.kind)~="string" or type(r.engraving)~="string" or not finite(r.level) then return nil end
  end
  for _,e in ipairs(data.incidents) do if type(e)~="table" or not finite(e.expires) or e.expires<data.clock or type(e.kind)~="string" then return nil end end
  for _,j in ipairs(data.jobs) do if type(j)~="table" or not finite(j.id) or not finite(j.expires) or not finite(j.target) or type(j.kind)~="string" then return nil end end
  for _,e in ipairs(data.legends) do if type(e)~="table" or not finite(e.tick) or type(e.text)~="string" or not finite(e.priority) then return nil end end
  if data.mood_arc~=false and (type(data.mood_arc)~="table" or not finite(data.mood_arc.expires) or data.mood_arc.expires<data.clock) then return nil end
  -- Remaining compatibility errors are contained by pcall in the adapter.
  return setmetatable(clone(data),Sim)
end
function Sim:close_incident(index, message)
  local e=table.remove(self.incidents,index)
  if e then self:legend(e.kind.."_close",message,e.open,3) end
end
function Sim:incident(kind, duration, text, severity)
  for _,e in ipairs(self.incidents) do if e.kind==kind then return e end end
  if #self.incidents>=Sim.CAPS.incidents then self:close_incident(1,"The watch stands down.") end
  local e={id=self:id(),kind=kind,severity=severity or 1,expires=self.clock+duration,opened=self.clock}
  e.open=self:legend(kind.."_open",text,0,kind=="ambush" and 5 or 3)
  self.incidents[#self.incidents+1]=e
  return e
end
function Sim:expire(target)
  -- Resolve timed arcs at their own tick, independent of delivery batch size.
  while true do
    local next_tick=target+1
    for _,e in ipairs(self.incidents) do next_tick=math.min(next_tick,e.expires) end
    if self.mood_arc then next_tick=math.min(next_tick,self.mood_arc.expires) end
    if self.announcement then next_tick=math.min(next_tick,self.announcement_until) end
    if next_tick>target then break end
    self.clock=next_tick
    if self.announcement and self.announcement_until<=next_tick then
      self.announcement=table.remove(self.announcements,1) or false
      self.announcement_until=self.announcement and next_tick+16 or 0
    end
    for i=#self.incidents,1,-1 do
      local e=self.incidents[i]
      if e.expires<=next_tick then
        local msg=e.kind=="caravan" and "The caravan departs; its findings join the archive." or
          e.kind=="mandate" and "The mandate lapses without a recorded decision." or "The watch stands down."
        if e.kind=="ambush" then self.cooldown=next_tick+120 end
        self:close_incident(i,msg)
      end
    end
    if self.mood_arc and self.mood_arc.expires<=next_tick then
      local arc=self.mood_arc; self.mood_arc=false
      local a={id=self:id(),name=arc.name,quality=arc.quality,room=arc.room,tick=next_tick,seq=arc.seq,parent=arc.parent}
      self.artifacts[#self.artifacts+1]=a
      self.last_artifact=next_tick
      local line=arc.dwarf.." has completed a masterwork: "..a.name.."."
      if #self.artifacts>1 then line=line.." Its patterns recall "..self.artifacts[#self.artifacts-1].name.."." end
      self:legend("artifact",line,arc.open,6)
    end
  end
end
function Sim:advance(target)
  target=math.max(self.clock,num(target))
  local elapsed=target-self.clock
  self:expire(target)
  self.clock=target
  self.stress=math.max(0,self.stress-elapsed/8)
  for i=#self.jobs,1,-1 do
    if self.jobs[i].expires<=target then
      local id=self.jobs[i].id
      for _,d in ipairs(self.dwarves) do if d.job==id then d.job=0 end end
      table.remove(self.jobs,i)
    else
      self.jobs[i].progress=math.max(0,math.min(1,(target-self.jobs[i].expires+24)/24))
    end
  end
  for _,d in ipairs(self.dwarves) do
    for _,k in ipairs(NEEDS) do d.needs[k]=math.max(0,d.needs[k]-elapsed/16) end
    d.mood=self.stress>12 and "strained" or (d.job~=0 and "focused" or "content")
    if self.mood_arc and d.name==self.mood_arc.dwarf then d.mood="inspired" end
  end
end
function Sim:tick(n) self:advance(self.clock+num(n)) end
function Sim:job(kind)
  local d=self.dwarves[1]
  for _,v in ipairs(self.dwarves) do if v.skills[kind]>d.skills[kind] then d=v end end
  for i=#self.jobs,1,-1 do if self.jobs[i].owner==d.id then table.remove(self.jobs,i) end end
  d.skills[kind]=d.skills[kind]+1
  for _,threshold in ipairs({5,20,80,320}) do
    if d.skills[kind]==threshold then
      local role=({plan="Planner",exec="Mechanic",edit="Mason",read="Archivist",trade="Broker",craft="Engraver"})[kind]
      self:legend("skill",d.name.." becomes a "..self:title(threshold).." "..role..".",0,2)
    end
  end
  local job={id=self:id(),kind=kind,owner=d.id,target=1+(self.counts.tools % #self.rooms),
    source_seq=self.seq,progress=0,expires=self.clock+24}
  self.jobs[#self.jobs+1]=job; d.job=job.id
  d.mood="focused"; d.needs.rest=math.min(100,d.needs.rest+2)
  d.needs.knowledge=math.min(100,d.needs.knowledge+1)
  d.needs.craft=math.min(100,d.needs.craft+1)
  d.needs.fellowship=math.min(100,d.needs.fellowship+1)
  d.needs[kind=="read" and "knowledge" or "craft"]=0
  if #self.jobs>Sim.CAPS.jobs then table.remove(self.jobs,1) end
end
function Sim:population(count, silent)
  count=num(count)
  self.crew=math.max(0,count+1-Sim.CAPS.dwarves)
  while #self.dwarves<math.min(Sim.CAPS.dwarves,count+1) do
    local d=self:dwarf("resident")
    if not silent then self:legend("migrant",d.name.." arrives to work below.",0,4) end
  end
  while #self.dwarves>count+1 do
    local d=table.remove(self.dwarves)
    for i=#self.jobs,1,-1 do if self.jobs[i].owner==d.id then table.remove(self.jobs,i) end end
    if not silent then self:legend("departure",d.name.." departs; the work is remembered.",0,4) end
  end
end
function Sim:inspire()
  if self.mood_arc or #self.artifacts>=Sim.CAPS.artifacts or self.clock-self.last_artifact<6000 then return end
  if self.counts.tools<150 and self.clock<4800 then return end
  local d=self.dwarves[1]; local best=0
  for _,v in ipairs(self.dwarves) do for _,k in ipairs(SKILLS) do if v.skills[k]>best then d,best=v,v.skills[k] end end end
  if best<20 then return end
  self.last_artifact=self.clock
  local name=PREFIX[Sim.roll(self.seed,self.seq,"artifact",#PREFIX)]..self.material.." "..self.subject
  local open=self:legend("inspiration",d.name.." claims a workshop. The work continues.",0,6)
  self.mood_arc={name=name,expires=self.clock+8+Sim.roll(self.seed,self.seq,"inspiration-time",5)-1,
    dwarf=d.name,quality=self:title(best),room=1,seq=self.seq,open=open,parent=#self.artifacts>0 and self.artifacts[#self.artifacts].id or 0}
  d.mood="inspired"
end
function Sim:push(e)
  if type(e)~="table" or num(e.seq)<=self.seq then return false end
  self:advance(e.tick)
  self.seq=num(e.seq)
  local p=type(e.payload)=="table" and e.payload or {}
  local k=e.kind
  if k=="embark" then self:legend("embark","The founders raise the gate of "..self.name..".",0,4)
  elseif k=="prompt" then
    self.counts.prompts=self.counts.prompts+1
    self.subject=Sim.safe(type(p.words)=="table" and p.words[1])
    self:legend("chapter","A new chapter begins: "..self.subject..".",0,1)
    self.rooms[1].engraving=self.subject
    self:job("plan")
  elseif k=="tool" then
    local kind="other"; for _,v in ipairs(KINDS) do if p.kind==v then kind=v end end
    self.counts.tools=self.counts.tools+1; self.counts.tool_kinds[kind]=self.counts.tool_kinds[kind]+1
    local jobkind=({web="trade",mcp="trade",task="plan",other="craft"})[kind] or kind
    self:job(jobkind)
    if kind=="web" or kind=="mcp" then self:incident("caravan",32,"A caravan reaches the gate, bearing "..self.subject..".") end
    if kind=="edit" then
      self.store=self.store+1
      if #self.items<Sim.CAPS.items then self.items[#self.items+1]={id=self:id(),kind="block",room=1,quality="worked"} end
    end
    self.material=({rs="steel",py="slate",ts="copper",lua="amber",go="iron"})[p.ext] or self.material
    local target=math.min(Sim.CAPS.rooms,3+math.floor(self.counts.tools/15))
    while #self.rooms<target do self:room(jobkind) end
    self:inspire()
  elseif k=="success" then
    self.stress=math.max(0,self.stress-6)
    for i=#self.incidents,1,-1 do if self.incidents[i].kind=="ambush" then
      self:close_incident(i,self.profile=="calm" and "The setback clears; work resumes." or "The raid is broken; work resumes."); self.cooldown=self.clock+120; self.failures={}
    end end
    for _,d in ipairs(self.dwarves) do d.job=0 end; self.jobs={}
  elseif k=="tool_failed" then
    self.counts.errors=self.counts.errors+1
    self.stress=math.min(30,self.stress+(self.profile=="calm" and 4 or 8))
    local f={}; for _,t in ipairs(self.failures) do if self.clock-t<=360 then f[#f+1]=t end end
    f[#f+1]=self.clock; while #f>6 do table.remove(f,1) end; self.failures=f
    if self.clock>=self.cooldown then
      local severity=#f>=6 and 3 or (#f>=3 and 2 or 1)
      local text=self.profile=="calm" and "A setback reaches the workshop; the watch gathers." or
        (self.profile=="chaos" and "Drums echo in the tunnels; an ambush reaches the gate." or "An ambush strikes the gate.")
      local incident=self:incident("ambush",240,text,severity)
      if severity>incident.severity then
        incident.severity=severity
        self:legend("escalation",self.profile=="calm" and "The watch reinforces the workshop." or (severity==3 and "A siege gathers at the gate." or "The ambush grows into a raid."),incident.open,5)
      end
    end
  elseif k=="wait_open" then
    self.counts.waits=self.counts.waits+1
    self.stress=math.min(30,self.stress+(self.profile=="calm" and 1 or 2))
    self:incident("mandate",240,"A mandate awaits judgment at the gate.")
  elseif k=="wait_resolved" then
    local outcome=({fulfilled="fulfilled",declined="declined"})[p.outcome] or "resolved"
    for i=#self.incidents,1,-1 do if self.incidents[i].kind=="mandate" then self:close_incident(i,"The mandate is "..outcome..". The work continues.") end end
  elseif k=="subagent_start" or k=="subagent_stop" then
    self.counts.subagents=num(p.count); self.counts.subagents_peak=math.max(self.counts.subagents_peak,self.counts.subagents)
    self:population(self.counts.subagents)
  elseif k=="compact" then
    self.counts.compactions=self.counts.compactions+1
    self:legend("year_end",string.format("Year %d closes with %d labors and %d named works.",self.year,self.counts.tools,#self.artifacts),0,5)
    for i=#self.incidents,1,-1 do self:close_incident(i,"The old gallery is sealed; the watch returns.") end
    self.jobs={}; self.items={}; for _,d in ipairs(self.dwarves) do d.job=0 end
    self.z=self.z+1; self.year=self.year+1; self.cave_until=self.clock+12
    for _,r in ipairs(self.rooms) do r.z=self.z end
    self:legend("cave_in","A deep rumble passes; the old gallery is sealed.",0,5)
  elseif k=="idle" then
    self.jobs={}; for _,d in ipairs(self.dwarves) do d.job=0; d.mood="content" end
    if self.clock-self.last_routine>=80 then
      self.last_routine=self.clock
      if #self.legends>0 then
        local past=self.legends[Sim.roll(self.seed,self.seq,"engraving",#self.legends)]
        self.rooms[1].engraving=past.text
        self.rooms[1].legend_id=past.id
      end
    end
  end
  self:advance(self.clock)
  return true
end
function Sim:reconcile(j)
  if num(j.seq)<self.seq then return end
  self:advance(j.tick)
  self.seq=num(j.seq)
  if self.gap_to~=self.seq then
    self.gap_to=self.seq
    self:legend("chronicle_gap","A passage of the chronicle is missing; totals are reconciled.",0,5)
  end
  for _,k in ipairs(COUNTERS) do self.counts[k]=num(j[k]) end
  for _,k in ipairs(KINDS) do self.counts.tool_kinds[k]=num((j.tool_kinds or {})[k]) end
  self:population(self.counts.subagents, true)
  for i=#self.incidents,1,-1 do self:close_incident(i,"The record is incomplete; the watch stands down.") end
  self.jobs={}; for _,d in ipairs(self.dwarves) do d.job=0 end
  self.z=self.counts.compactions; self.year=self.z+1
  while #self.rooms<math.min(Sim.CAPS.rooms,3+math.floor(self.counts.tools/15)) do self:room("archive") end
end
function Sim:observe(state)
  self.wealth=math.max(self.wealth,num(state.lines_added))
  self.quarry=math.max(self.quarry,num(state.lines_removed))
  for _,r in ipairs(self.rooms) do r.level=math.min(5,1+math.floor(self.wealth/500)) end
end
function Sim:configure(params)
  params=params or {}
  if params.difficulty=="calm" or params.difficulty=="classic" or params.difficulty=="chaos" then self.profile=params.difficulty end
  if type(params.fortress)=="string" and #params.fortress<=24 and params.fortress:match("^[A-Za-z][A-Za-z -]+$") and params.fortress~=self.name then
    self.name=params.fortress
    self:legend("renamed","The fortress is now known as "..self.name..".",0,3)
  end
end
return Sim

end)()
local View = (function()
-- Stateless layout/renderer. Simulation tables are read only here.
local View = {}
View.colours = {neutral={0.38,0.49,0.56}, amber={0.60,0.43,0.20}, red={0.57,0.28,0.28},
  violet={0.52,0.38,0.64}, wall={0.25,0.32,0.38}, floor={0.16,0.22,0.23}, green={0.30,0.43,0.33}}
function View.season(pct)
  return ({"spring","summer","autumn","winter"})[1+math.min(3,math.floor(math.max(0,tonumber(pct) or 0)/25))]
end
function View.layout(world,w,h)
  local strip=math.max(1,math.min(40,math.floor(w*0.18)))
  local cols=w>=160 and 2 or 1
  local room_w=math.max(4,math.floor(strip/cols)-1)
  local room_h=h>=45 and 8 or 6
  local rows=math.max(0,math.floor((h-7)/(room_h+1)))
  local out={w=w,h=h,strip=strip,rooms={},centre={x=strip,y=0,w=math.max(0,w-2*strip),h=h}}
  if w<60 or h<16 then out.decoration={}; return out end
  local slots=rows*cols
  for i,r in ipairs(world.rooms) do
    local side=(i-1)//math.max(1,slots)
    if side>1 or (side==1 and w<120 and i>slots+1) then break end
    local slot=(i-1)%math.max(1,slots)
    local col=slot%cols; local row=slot//cols
    local x=side==0 and (1+col*(room_w+1)) or (w-strip+col*(room_w+1))
    if x+room_w<=w and room_w>=4 then
      out.rooms[#out.rooms+1]={id=r.id,index=i,x=x,y=3+row*(room_h+1),w=room_w,h=room_h}
    end
  end
  out.decoration=View.decorate(world,out)
  return out
end
local function glyph(kind)
  return ({plan="?",exec="=",edit="=",read="?",trade="*",craft="=",rest="~",archive=":"})[kind] or "="
end
function View.decorate(world,layout)
  local w,h,strip,rooms=layout.w,layout.h,layout.strip,layout.rooms
  local layers,seen={{},{},{},{},{},{}},{}
  local function put(x,y,ch,colour,priority)
    if x<0 or y<0 or x>=w or y>=h or (x>=strip and x<w-strip) or ch==" " then return end
    local key=y*w+x
    if seen[key] then return end
    seen[key]=true
    local list=layers[(priority or 3)+1]
    list[#list+1]={x=x,y=y,ch=ch,c=View.colours[colour] or View.colours.neutral,floor=colour=="floor"}
  end
  local function text(x,y,s,max,colour,priority)
    for i=1,math.min(#s,max) do put(x+i-1,y,s:sub(i,i),colour,priority) end
  end
  for _,r in ipairs(rooms) do
    local source=world.rooms[r.index]
    local label=source.kind:sub(1,math.max(0,r.w-4))
    text(r.x+2,r.y,label,r.w-3,"neutral",2)
    put(r.x+r.w-1,r.y+2,"+","amber",2)
    put(r.x+1,r.y+1,glyph(source.kind),"neutral",2)
    if source.engraving~="" then put(r.x+1,r.y+r.h-2,"'","violet",3) end
    for x=r.x,r.x+r.w-1 do put(x,r.y,"#","wall",3); put(x,r.y+r.h-1,"#","wall",3) end
    for y=r.y+1,r.y+r.h-2 do put(r.x,y,"#","wall",3); put(r.x+r.w-1,y,"#","wall",3) end
    for y=r.y+1,r.y+r.h-2 do for x=r.x+1,r.x+r.w-2 do
      if (x+y)%3==0 then put(x,y,".","floor",4) end
    end end
    if source.level>1 then put(r.x+r.w-2,r.y+1,tostring(source.level),"amber",2) end
  end
  -- Seeded rock/veins provide a visible embark without inventing earned rooms.
  for y=3,h-3 do for _,left in ipairs({0,w-strip}) do for x=left,left+strip-1 do
    local n=(x*17+y*31+world.seed)%13
    if n<2 then put(x,y,n==0 and ":" or ".","floor",5) end
  end end end
  if world.z>0 then text(0,h-3,"< sealed gallery",strip,"wall",4) end
  return layers
end
function View.render(fx,world,layout,state,phase)
  local w,h,strip=layout.w,layout.h,layout.strip
  if w<1 or h<1 then return end
  local occupied={}
  local density=math.max(0.1,math.min(3,tonumber((state.params or {}).density) or 1))
  local budget=math.floor(w*h*math.min(0.25,0.15*density))
  local drawn=fx:count()
  local function put(x,y,ch,colour,priority)
    if x<0 or y<0 or x>=w or y>=h or (x>=strip and x<w-strip) or ch==" " then return end
    local key=y*w+x
    local cap=priority==0 and math.floor(w*h*0.25) or budget
    if occupied[key] or drawn>=cap then return end
    occupied[key]=true
    local c=type(colour)=="table" and colour or (View.colours[colour] or View.colours.neutral)
    fx:put(x,y,ch,c[1],c[2],c[3]); drawn=drawn+1
  end
  local function text(x,y,s,max,colour,priority)
    for i=1,math.min(#s,max) do put(x+i-1,y,s:sub(i,i),colour,priority) end
  end
  local season=View.season(state.context_pct)
  text(0,0,world.name,strip,"neutral",0)
  text(0,1,string.format("Y%d %s",world.year,season),strip,"green",0)
  text(w-strip,0,string.format("%dd +%dc",#world.dwarves,world.crew),strip,"neutral",0)
  text(w-strip,1,string.format("z%d $%d",world.z,world.wealth),strip,"neutral",0)
  -- Fixed edge segments; no scrolling banner through foreground text.
  local latest=world.announcement
  if latest and h>3 then
    local labels={embark="Gate raised",chapter="New chapter",migrant="Specialist in",departure="Departure",
      inspiration="Strange mood",artifact="Masterwork",caravan_open="Caravan arrives",caravan_close="Caravan leaves",
      mandate_open="Decision waits",mandate_close="Decision noted",ambush_open="Watch gathers",escalation="Gate reinforced",
      ambush_close="Work resumes",cave_in="Gallery sealed",year_end="Year closes",chronicle_gap="History gap",renamed="New name"}
    local left=labels[latest.kind] or "Chronicle"
    local right=world.subject
    if latest.kind=="migrant" or latest.kind=="departure" or latest.kind=="inspiration" or latest.kind=="artifact" then right=latest.text:match("^(%w+)") or right end
    if latest.kind=="chronicle_gap" then right="Totals kept" end
    local function clip(s) return #s>strip and (s:sub(1,math.max(0,strip-3)).."...") or s end
    text(0,h-2,clip(left),strip,"neutral",0)
    text(w-strip,h-2,clip(right),strip,"neutral",0)
  end
  local rooms=layout.rooms
  local jobs={}
  for _,j in ipairs(world.jobs) do jobs[j.id]=j end
  for i,d in ipairs(world.dwarves) do
    local job=jobs[d.job]
    local room=#rooms>0 and rooms[((job and job.target or i)-1)%#rooms+1] or nil
    local x,y=0,math.min(h-1,3+i)
    if room then x=room.x+2+((i-1)%math.max(1,room.w-4)); y=room.y+2+((i-1)//math.max(1,room.w-4))%(room.h-3) end
    local col=d.mood=="inspired" and "violet" or (d.mood=="strained" and "amber" or "neutral")
    put(x,y,d.role=="founder" and "@" or "d",col,0)
    local mark=job and glyph(job.kind) or "~"
    if state.mode=="thinking" and d.role=="founder" then mark="?" end
    if state.mode=="idle" and (tonumber(state.age) or 0)>60 then mark="z" end
    if state.mode=="tool" and math.floor(phase*3+i)%2==0 then mark="*" end
    put(x+1,y,mark,col,0)
  end
  if world.crew>0 then text(w-strip,h-4,"dd crew",strip,"neutral",0) end
  for i,e in ipairs(world.incidents) do
    local x=w-strip+math.min(strip-1,2+i*2)
    local y=math.min(h-3,3+i)
    local ch,col="!","red"
    if e.kind=="caravan" then ch,col="*","green"; x=w-strip+1+math.floor(phase*2)%math.max(1,strip-2)
    elseif e.kind=="mandate" then ch,col="?","amber" end
    put(x,y,ch,col,0)
    if world.profile=="chaos" and e.kind=="ambush" then put(x+1,y,"!",col,0) end
  end
  for i,a in ipairs(world.artifacts) do
    if #rooms>0 then local r=rooms[(a.room-1)%#rooms+1]; put(r.x+1+(i%math.max(1,r.w-2)),r.y+r.h-2,"*","violet",1) end
  end
  if #rooms>0 then
    put(rooms[1].x+1,rooms[1].y+2,world.z>0 and ">" or "+","amber",1)
    for i,item in ipairs(world.items) do
      local r=rooms[(item.room-1)%#rooms+1]
      put(r.x+1+i%math.max(1,r.w-2),r.y+r.h-2,":","wall",4)
    end
  end
  if world.z>0 then text(0,h-3,"< sealed gallery",strip,"wall",4) end
  if world.cave_until>world.clock or state.mode=="compacting" then
    for x=0,strip-1 do put(x,math.min(h-1,2+(x+math.floor(phase*4))%math.max(1,h-4)),"'","amber",1) end
  end
  if state.mode=="error" and (tonumber(state.age) or 0)<3 then put(w-2,2,"!","red",0) end
  local floor_colour=({spring={0.16,0.23,0.19},summer={0.22,0.23,0.16},autumn={0.25,0.19,0.15},winter={0.17,0.21,0.27}})[season]
  local layers=layout.decoration or View.decorate(world,layout)
  for _,layer in ipairs(layers) do for _,v in ipairs(layer) do
    if drawn>=budget then return end
    put(v.x,v.y,v.ch,v.floor and floor_colour or v.c)
  end end
end
return View

end)()
local M = (function()
-- Included after local Sim and View by bundle.py. Host API is optional in harness.
local M = {}
local world, projected, layout, saved=nil,nil,nil,nil
local W,H,SEED,T,elapsed=0,0,0,0,0,0
local signature=""
function M.init(ctx)
  W,H,SEED=ctx.w,ctx.h,ctx.seed or 0
  world,projected,layout,saved=nil,nil,nil,nil
  T,elapsed,signature=0,0,""
end
function M.resize(ctx)
  if W==0 and H==0 then M.init(ctx); return end
  W,H=ctx.w,ctx.h; layout=nil
end
function M.restore(record) saved=record end
function M.export()
  if not world then return nil end
  return {schema_version=Sim.VERSION,seq=world.seq,counter_digest=Sim.digest(world.counts),world_state=world:snapshot(),
    legends=(projected or world).legends,summary=world.summary,
    status={name=world.name,year=world.year,season=(layout and layout.season) or "spring",population=#world.dwarves,
      crew=world.crew,wealth=world.wealth,stress=(projected or world).stress,z=world.z}}
end
function M.step(dt,state)
  local j=state.journey or {}
  local identity=tostring(j.repo or "fortress")..":"..tostring(j.session_id or SEED)..":"..tostring(j.epoch or "preview")..":2"
  if not world or world.identity~=identity then
    world=Sim.new(Sim.hash(identity),identity)
    if saved and saved.counter_digest and saved.world_state then
      local ok,restored=pcall(function()
        local candidate=Sim.restore(saved.world_state,identity)
        if candidate and Sim.digest(candidate.counts)==saved.counter_digest then candidate:advance(candidate.clock); return candidate end
      end)
      if ok and restored then world=restored end
    end
    saved=nil; elapsed=0; layout=nil
  end
  if (state.params or {}).paused then
    if not projected then projected=Sim.restore(world:snapshot(),identity) end
    if not layout then layout=View.layout(world,W,H) end
    return
  end
  local speed=tonumber((state.mod or {}).speed) or 1
  if speed==0 then return end
  local real_dt=math.max(0,math.min(1,dt/speed))
  T=T+dt; elapsed=elapsed+real_dt
  world:configure(state.params)
  local recent=j.recent or {}
  local last_seq=tonumber(j.seq) or 0
  if j.schema_version==2 and last_seq>world.seq then
    local first=recent[1]
    if not first or (tonumber(first.seq) or 0)>world.seq+1 then
      world:reconcile(j)
    else
      for _,e in ipairs(recent) do
        if (tonumber(e.seq) or 0)>world.seq+1 then world:reconcile(j); break end
        world:push(e)
      end
      if world.seq<last_seq or Sim.digest(world.counts)~=j.counter_digest then world:reconcile(j) end
    end
    elapsed=0
  elseif not j.schema_version and world.seq==0 and (tonumber(j.tools) or 0)>0 then
    -- Old writers have aggregates only; never interpret their unsequenced ring as history.
    local totals={}; for k,v in pairs(j) do totals[k]=v end
    totals.seq=1; totals.tick=0; world:reconcile(totals)
  end
  world:observe(state)
  -- Keep committed history at the event watermark; projection advances between hooks.
  -- A delayed hook can then be applied at its actual tick without rewinding history.
  local tick=world.clock+math.floor(elapsed*4)
  local sig=tostring(world.seq)..":"..tick..":"..W..":"..H..":"..#world.rooms..":"..world.name..":"..world.wealth..":"..world.profile
  if sig~=signature or not projected then
    signature=sig
    projected=Sim.restore(world:snapshot(),identity)
    projected:advance(tick)
  end
  local decor_key=world.wealth..":"..world.subject..":"..world.z
  if not layout or layout.w~=W or layout.h~=H or layout.room_count~=#world.rooms or layout.decor_key~=decor_key then
    layout=View.layout(world,W,H); layout.room_count=#world.rooms; layout.decor_key=decor_key
  end
  layout.season=View.season(state.context_pct)
end
function M.render(fx,state)
  if world and layout then View.render(fx,projected or world,layout,state,T) end
end
return M

end)()

function init(ctx) M.init(ctx) end
function resize(ctx) M.resize(ctx) end
function step(dt,state) M.step(dt,state) end
function render(fx,state) M.render(fx,state) end
function foreground_halo() return 1 end
function checkpoint() return M.export() end
function restore(data) M.restore(data) end
