"""Bundle the standalone world motifs into plugins/fx/world.lua."""
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
FX = ROOT / "plugins" / "fx"
MOTIFS = [
    "forest", "skyline", "reef", "circuit", "office",
    "sakura", "kana", "shrine", "hangar", "dojo", "hud",
    "studyroom", "sparkfield", "dust",
]
CUT = "\nfunction init(ctx)"

FOOT = """
local MOTIFS = {
%(table)s
}
local ORDER = { %(order)s }

local CTX = nil
local CURRENT = nil
local ACTIVE = nil
local SAVED = nil
local INITIALIZED = {}

local function choose(state)
  local mood = state.mood or {}
  local want = mood.motif
  if want == "fortress" then return "office" end
  if type(want) == "string" and MOTIFS[want] then return want end
  local j = state.journey or {}
  local key = j.repo
  if type(key) ~= "string" or key == "" then
    key = tostring((CTX and CTX.seed) or 0)
  end
  local pick = sbg.pick(ORDER, key)
  if type(pick) == "string" and MOTIFS[pick] then return pick end
  return "office"
end

function init(ctx)
  CTX = ctx
  CURRENT, ACTIVE = nil, nil
  INITIALIZED = {}
end

function step(dt, state)
  if CTX == nil then return end
  local want = choose(state)
  if want ~= CURRENT then
    CURRENT = want
    ACTIVE = MOTIFS[want]
    if not INITIALIZED[want] then ACTIVE.init(CTX); INITIALIZED[want] = true
    elseif ACTIVE.resize then ACTIVE.resize(CTX) end
    if SAVED and ACTIVE.restore then ACTIVE.restore(SAVED); SAVED = nil end
  end
  ACTIVE.step(dt, state)
end

function resize(ctx)
  CTX = ctx
  if ACTIVE then
    if ACTIVE.resize then ACTIVE.resize(ctx) else ACTIVE.init(ctx) end
  end
end

function restore(data) SAVED = data end
function foreground_halo() return (ACTIVE and ACTIVE.export) and 1 or 0 end
function checkpoint() if ACTIVE and ACTIVE.export then return ACTIVE.export() end end

function render(fx, state)
  if ACTIVE == nil then return end
  ACTIVE.render(fx, state)
end
"""


def fortress():
    parts = ["-- GENERATED by scripts/world/bundle.py; edit plugins/fx/fortress/*.lua.\n"]
    for name, local in (("sim", "Sim"), ("render", "View"), ("adapter", "M")):
        body = (FX / "fortress" / f"{name}.lua").read_text(encoding="utf-8")
        parts.append(f"local {local} = (function()\n{body}\nend)()\n")
    parts.append("\nfunction init(ctx) M.init(ctx) end\nfunction resize(ctx) M.resize(ctx) end\nfunction step(dt,state) M.step(dt,state) end\nfunction render(fx,state) M.render(fx,state) end\nfunction foreground_halo() return 1 end\nfunction checkpoint() return M.export() end\nfunction restore(data) M.restore(data) end\n")
    return "".join(parts)


def bundle(motifs=MOTIFS):
    parts = []
    for name in motifs:
        source = fortress() if name == "office" else (FX / f"{name}.lua").read_text(encoding="utf-8")
        body, sep, _ = source.partition(CUT)
        if not sep:
            raise SystemExit(f"{name}.lua has no top-level init(ctx)")
        parts.append("local %s = (function()\n%s\n  return M\nend)()\n\n" % (name.capitalize(), body.rstrip()))
    foot = FOOT % {
        "table": "\n".join("  %s = %s," % (m, m.capitalize()) for m in motifs),
        "order": ", ".join('"%s"' % m for m in motifs),
    }
    return "".join(parts) + foot


def main(argv):
    text = bundle()
    standalone = fortress()
    if "--check" in argv:
        for name in ("office", "fortress"):
            if (FX / f"{name}.lua").read_text(encoding="utf-8") != standalone:
                print(f"{name}.lua is stale; run scripts/world/bundle.py", file=sys.stderr)
                return 1
        current = (FX / "world.lua").read_text(encoding="utf-8")
        if current != text:
            print("world.lua is stale; run scripts/world/bundle.py", file=sys.stderr)
            return 1
        print("world.lua up to date")
        return 0
    for name in ("office", "fortress"):
        (FX / f"{name}.lua").write_text(standalone, encoding="utf-8")
    (FX / "world.lua").write_text(text, encoding="utf-8")
    print("world.lua: %d lines, %d motifs" % (text.count("\n"), len(MOTIFS)))
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
