"""Bundle the Fortress modules into plugins/fx/fortress.lua and plugins/fx/world.lua."""
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
FX = ROOT / "plugins" / "fx"
PARTS = (("glyphs", "Glyphs"), ("sim", "Sim"), ("life", "Life"), ("plaque", "Plaque"), ("landscape", "Landscape"), ("studioview", "Studioview"), ("studio", "Studio"), ("render", "View"), ("adapter", "M"))
OUTPUTS = ("fortress", "world")


def fortress():
    parts = ["-- GENERATED by scripts/world/bundle.py; edit plugins/fx/fortress/*.lua.\n"]
    for name, local in PARTS:
        body = (FX / "fortress" / f"{name}.lua").read_text(encoding="utf-8")
        parts.append(f"local {local} = (function()\n{body}\nend)()\n")
        if name == "render":
            parts.append("View.landscape = Landscape\n")
            parts.append("View.studioview = Studioview\n")
    parts.append("\nfunction init(ctx) M.init(ctx) end\nfunction resize(ctx) M.resize(ctx) end\nfunction step(dt,state) M.step(dt,state) end\nfunction render(fx,state) M.render(fx,state) end\nfunction foreground_halo() return 1 end\nfunction checkpoint() return M.export() end\nfunction restore(data) M.restore(data) end\n")
    return "".join(parts)


def main(argv):
    text = fortress()
    if "--check" in argv:
        for name in OUTPUTS:
            if (FX / f"{name}.lua").read_text(encoding="utf-8") != text:
                print(f"{name}.lua is stale; run scripts/world/bundle.py", file=sys.stderr)
                return 1
        print("world.lua up to date")
        return 0
    for name in OUTPUTS:
        (FX / f"{name}.lua").write_text(text, encoding="utf-8")
    print("world.lua: %d lines (Fortress)" % text.count("\n"))
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
