#!/usr/bin/env python3
"""One marketplace, two agents.

`plugins.json` at the repository root is the only place a plugin is declared.
Everything else is derived:

    plugins.json
      ├─ .claude-plugin/marketplace.json     rendered for Claude Code
      ├─ .agents/plugins/marketplace.json    rendered for Codex
      └─ <project>/plugins/<name>/           the plugin itself
             ├─ .claude-plugin/plugin.json   rendered
             └─ .codex-plugin/plugin.json    rendered (adds `skills` + `interface`)

Subcommands
    sync        render every manifest from plugins.json (use --check for drift only)
    check       validate the catalog, the rendered manifests, and each plugin
    status      what each agent currently has registered and installed
    install     register the marketplace and install every plugin in both agents
    uninstall   remove the marketplace and its plugins from both agents

Dependency-free (stdlib only) and safe to re-run: every step is idempotent.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import shutil
import subprocess
import sys
import time
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

try:
    import tomllib
except ModuleNotFoundError:
    tomllib = None  # type: ignore[assignment]


def ensure_modern_python() -> None:
    """Re-exec the CLI under Python 3.11+ when macOS `/usr/bin/python3` is selected."""
    if sys.version_info >= (3, 11):
        return
    current = str(Path(sys.executable).resolve())
    for name in ("python3.14", "python3.13", "python3.12", "python3.11"):
        candidate = shutil.which(name)
        if candidate and str(Path(candidate).resolve()) != current:
            os.execv(candidate, [candidate, *sys.argv])
    raise SystemExit("scripts/plugins.py requires Python 3.11+ (tomllib)")

ROOT = Path(__file__).resolve().parents[1]
CATALOG = ROOT / "plugins.json"
CLAUDE_CORE_DELIVERY = "claude-core"
CLAUDE_MARKETPLACE = ROOT / ".claude-plugin" / "marketplace.json"
CODEX_MARKETPLACE = ROOT / ".agents" / "plugins" / "marketplace.json"
CODEX_CONFIG = Path.home() / ".codex" / "config.toml"
MEMORY_CONFIG = Path.home() / ".config" / "obsidian-memory" / "config.json"
MEMORY_INSTALLER = ROOT / "wiki" / "scripts" / "install.py"

GENERATED_NOTE = "GENERATED by scripts/plugins.py from plugins.json — do not edit by hand."


class Problem(RuntimeError):
    """A validation failure worth stopping for."""


# --------------------------------------------------------------------------- #
# catalog
# --------------------------------------------------------------------------- #
def load_catalog() -> dict[str, Any]:
    try:
        catalog = json.loads(CATALOG.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise Problem(f"plugins.json: {exc}") from exc

    market = catalog.get("marketplace")
    if not isinstance(market, dict) or not market.get("name"):
        raise Problem("plugins.json: marketplace.name is required")
    plugins = catalog.get("plugins")
    if not isinstance(plugins, list) or not plugins:
        raise Problem("plugins.json: plugins must be a non-empty array")

    seen: set[str] = set()
    for entry in plugins:
        name = entry.get("name")
        source = entry.get("source")
        if not name or not isinstance(name, str):
            raise Problem("plugins.json: every plugin needs a name")
        if name in seen:
            raise Problem(f"plugins.json: duplicate plugin name {name}")
        seen.add(name)
        if not isinstance(source, str) or not source.startswith("./"):
            raise Problem(f"{name}: source must be a repo-relative path like ./project/plugins/{name}")
        if not isinstance(entry.get("version"), str) or not entry["version"]:
            raise Problem(f"{name}: version is required in plugins.json")
        if not entry.get("description"):
            raise Problem(f"{name}: description is required (users read it when installing)")
        delivery = entry.get("claude_delivery")
        if delivery is not None and delivery != CLAUDE_CORE_DELIVERY:
            raise Problem(f"{name}: claude_delivery must be \"{CLAUDE_CORE_DELIVERY}\" when present")
    return catalog


def delivered_by_claude_core(entry: dict[str, Any]) -> bool:
    """True when claude-core links this plugin's skills into ~/.claude instead of a marketplace copy."""
    return entry.get("claude_delivery") == CLAUDE_CORE_DELIVERY


def claude_marketplace_needed(catalog: dict[str, Any]) -> bool:
    return any(not delivered_by_claude_core(entry) for entry in catalog["plugins"])


def claude_core_state(source: Path) -> str:
    """Postcondition for a claude-core delivered plugin: every skill directory is linked live.

    The link target must be this checkout's skill directory itself, so a stale marketplace
    copy or a hand-made link elsewhere is reported rather than trusted.
    """
    skills = source / "skills"
    names = sorted(child.name for child in skills.iterdir() if child.is_dir()) if skills.is_dir() else []
    if not names:
        return "MISSING"
    for name in names:
        link = Path.home() / ".claude" / "skills" / name
        if not link.is_symlink() or Path(os.readlink(link)) != skills / name or not link.exists():
            return "UNLINKED"
    return "claude-core"


def plugin_dir(entry: dict[str, Any]) -> Path:
    return ROOT / str(entry["source"]).removeprefix("./")


def marketplace_name(catalog: dict[str, Any]) -> str:
    return str(catalog["marketplace"]["name"])


def plugin_id(catalog: dict[str, Any], entry: dict[str, Any]) -> str:
    return f"{entry['name']}@{marketplace_name(catalog)}"


def plugin_version(entry: dict[str, Any]) -> str:
    """Return the catalog version; generated manifests are never an input."""
    return str(entry["version"])


# --------------------------------------------------------------------------- #
# rendering
# --------------------------------------------------------------------------- #
def render_marketplace(catalog: dict[str, Any]) -> dict[str, Any]:
    market = catalog["marketplace"]
    rendered: dict[str, Any] = {
        "$comment": GENERATED_NOTE,
        "name": market["name"],
        "owner": market.get("owner", {"name": "unknown"}),
    }
    if market.get("description"):
        rendered["description"] = market["description"]
    entries = []
    for entry in catalog["plugins"]:
        item = {
            "name": entry["name"],
            "source": entry["source"],
            "description": entry["description"],
            "version": plugin_version(entry),
        }
        for optional in ("displayName", "category", "keywords", "license", "homepage", "author"):
            if entry.get(optional):
                item[optional] = entry[optional]
        entries.append(item)
    rendered["plugins"] = entries
    # `renames` is deliberately NOT rendered. Here it means "marketplaces this one
    # supersedes", and cmd_install reads it straight from plugins.json to retire them.
    # Claude Code's manifest schema reads a `renames` target as a *plugin* name, so
    # emitting ours made `claude plugin validate` fail on every entry (target-missing)
    # even though loading worked.
    return rendered


def render_plugin_manifests(catalog: dict[str, Any], entry: dict[str, Any]) -> dict[Path, dict[str, Any]]:
    """Both agents get the same identity; Codex additionally needs skills + interface."""
    directory = plugin_dir(entry)
    base: dict[str, Any] = {
        "name": entry["name"],
        "version": plugin_version(entry),
        "description": entry["description"],
        "author": entry.get("author") or catalog["marketplace"].get("owner", {"name": "unknown"}),
        "license": entry.get("license", "MIT"),
        "keywords": entry.get("keywords", []),
    }
    claude = dict(base)
    codex = dict(base)
    codex["skills"] = "./skills/"
    codex_extra = entry.get("codex") or {}
    codex["interface"] = {
        "displayName": entry.get("displayName", entry["name"]),
        "shortDescription": codex_extra.get("shortDescription", entry["description"]),
        "longDescription": codex_extra.get("longDescription", entry["description"]),
        "developerName": catalog["marketplace"].get("owner", {}).get("name", "unknown"),
        "category": entry.get("category", "Productivity"),
        "capabilities": codex_extra.get("capabilities", ["Read"]),
        "defaultPrompt": codex_extra.get("defaultPrompt", []),
    }
    return {
        directory / ".claude-plugin" / "plugin.json": claude,
        directory / ".codex-plugin" / "plugin.json": codex,
    }


def write_json(path: Path, payload: dict[str, Any], check_only: bool) -> bool:
    """Returns True when the file changed (or would change under --check)."""
    text = json.dumps(payload, indent=2) + "\n"
    current = path.read_text(encoding="utf-8") if path.is_file() else None
    if current == text:
        return False
    if not check_only:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")
    return True


def cmd_sync(args: argparse.Namespace) -> int:
    catalog = load_catalog()
    changed: list[Path] = []

    for path, payload in (
        (CLAUDE_MARKETPLACE, render_marketplace(catalog)),
        (CODEX_MARKETPLACE, render_marketplace(catalog)),
    ):
        if write_json(path, payload, args.check):
            changed.append(path)

    for entry in catalog["plugins"]:
        directory = plugin_dir(entry)
        if not directory.is_dir():
            raise Problem(f"{entry['name']}: {directory.relative_to(ROOT)} does not exist")
        for path, payload in render_plugin_manifests(catalog, entry).items():
            if write_json(path, payload, args.check):
                changed.append(path)

    for path in changed:
        print(("would update " if args.check else "updated ") + str(path.relative_to(ROOT)))
    if not changed:
        print(f"all manifests match plugins.json ({len(catalog['plugins'])} plugins)")
    if args.check and changed:
        print("\nrun: python3 scripts/plugins.py sync", file=sys.stderr)
        return 1
    return 0


# --------------------------------------------------------------------------- #
# validation
# --------------------------------------------------------------------------- #
def check_plugin(entry: dict[str, Any]) -> list[str]:
    problems: list[str] = []
    directory = plugin_dir(entry)
    name = entry["name"]

    if not directory.is_dir():
        return [f"{name}: missing directory {directory.relative_to(ROOT)}"]

    for manifest in (".claude-plugin/plugin.json", ".codex-plugin/plugin.json"):
        path = directory / manifest
        if not path.is_file():
            problems.append(f"{name}: missing {manifest}")
            continue
        try:
            data = json.loads(path.read_text(encoding="utf-8"))
        except json.JSONDecodeError as exc:
            problems.append(f"{name}/{manifest}: invalid JSON: {exc}")
            continue
        if data.get("name") != name:
            problems.append(f"{name}/{manifest}: name is {data.get('name')!r}")

    skills = directory / "skills"
    if not skills.is_dir():
        problems.append(f"{name}: no skills/ directory — nothing for an agent to load")
        return problems

    found = 0
    for skill_dir in sorted(skills.iterdir()):
        skill = skill_dir / "SKILL.md"
        if not skill.is_file():
            continue
        found += 1
        text = skill.read_text(encoding="utf-8")
        if not text.startswith("---\n"):
            problems.append(f"{name}/{skill_dir.name}: SKILL.md needs YAML frontmatter")
            continue
        front = text[4 : text.find("\n---\n", 4)]
        if f"name: {skill_dir.name}" not in front:
            problems.append(f"{name}/{skill_dir.name}: frontmatter name must match the directory")
        description = next((line for line in front.splitlines() if line.startswith("description:")), "")
        if len(description) < 80:
            problems.append(f"{name}/{skill_dir.name}: description too thin to trigger reliably")
        if len(description) > 1200:
            problems.append(f"{name}/{skill_dir.name}: description over the practical budget")
    if found == 0:
        problems.append(f"{name}: skills/ contains no <skill>/SKILL.md")
    return problems


TEST_COUNT_PATTERNS = (re.compile(r"Ran (\d+) tests?"), re.compile(r"(?m)^\s*(\d+) pass\s*$"))


def count_tests(output: str) -> int:
    """Sum the test counts a child check printed, in the shapes verify-run.py recognizes.

    The umbrella gate swallows successful child output, so without this the evidence
    ledger records a green run as VACUOUS. Only real runner summaries count; a check
    script's own "ok" lines are not tests.
    """
    return sum(int(match) for pattern in TEST_COUNT_PATTERNS for match in pattern.findall(output))


# (project dir, command run from inside that dir)
PROJECT_CHECKS: tuple[tuple[str, list[str]], ...] = (
    ("wiki", [sys.executable, "scripts/check.py"]),
    ("codex-pair", ["bash", "scripts/check.sh"]),
    ("chatgpt-consult", ["bun", "run", "check"]),
    ("claude-core", [sys.executable, "scripts/manage.py", "check"]),
    ("qwen-gsd", [sys.executable, "scripts/check.py"]),
    ("chrome-cdp", [sys.executable, "scripts/check.py"]),
)


def cmd_check(args: argparse.Namespace) -> int:
    catalog = load_catalog()
    problems: list[str] = []

    rendered = render_marketplace(catalog)
    for path in (CLAUDE_MARKETPLACE, CODEX_MARKETPLACE):
        if not path.is_file():
            problems.append(f"{path.relative_to(ROOT)} missing — run `plugins.py sync`")
            continue
        try:
            current = json.loads(path.read_text(encoding="utf-8"))
        except json.JSONDecodeError as exc:
            problems.append(f"{path.relative_to(ROOT)}: invalid JSON: {exc}")
            continue
        if current != rendered:
            problems.append(f"{path.relative_to(ROOT)} is stale — run `plugins.py sync`")

    for entry in catalog["plugins"]:
        problems.extend(check_plugin(entry))

    label = f"catalog + {len(catalog['plugins'])} plugin(s)"
    print(f"{'FAIL' if problems else 'ok  '} {label}")
    for problem in problems:
        print(f"  - {problem}")

    if not args.fast:
        started = time.monotonic()
        tests_ran = 0
        suite = ROOT / "tests" / "test_plugins.py"
        if suite.is_file():
            result = subprocess.run(
                [sys.executable, str(suite)], cwd=ROOT, capture_output=True, text=True, check=False
            )
            ok = result.returncode == 0
            tests_ran += count_tests(result.stdout + result.stderr)
            print(f"{'ok  ' if ok else 'FAIL'} workspace tests")
            if not ok:
                for line in (result.stdout + result.stderr).strip().splitlines()[-15:]:
                    print(f"  | {line}")
                problems.append("workspace tests failed")

        for name, command in PROJECT_CHECKS:
            cwd = ROOT / name
            if not cwd.is_dir():
                problems.append(f"{name}: project directory is missing")
                continue
            if command[0] == "bun" and shutil.which("bun") is None:
                print(f"skip {name}: bun not on PATH")
                continue
            result = subprocess.run(command, cwd=cwd, capture_output=True, text=True, check=False)
            ok = result.returncode == 0
            tests_ran += count_tests(result.stdout + result.stderr)
            print(f"{'ok  ' if ok else 'FAIL'} {name} project checks")
            if not ok:
                tail = (result.stdout + result.stderr).strip().splitlines()[-15:]
                for line in tail:
                    print(f"  | {line}")
                problems.append(f"{name} project checks failed")
        print(f"\nRan {tests_ran} tests in {time.monotonic() - started:.3f}s\n")
        print("OK" if not problems else f"FAILED (failures={len(problems)})")

    return 1 if problems else 0


# --------------------------------------------------------------------------- #
# agent wiring
# --------------------------------------------------------------------------- #
def run(command: list[str], allow_failure: bool = False, quiet: bool = False) -> subprocess.CompletedProcess[str]:
    if not quiet:
        print("+", " ".join(command))
    result = subprocess.run(command, text=True, capture_output=True, check=False)
    if result.returncode and not allow_failure:
        raise Problem(f"{' '.join(command)} failed:\n{(result.stdout + result.stderr).strip()}")
    return result


def codex_output(command: list[str]) -> str:
    """Codex reports marketplace-load errors on stderr, so read both streams."""
    if shutil.which("codex") is None:
        return ""
    result = run(command, allow_failure=True, quiet=True)
    return result.stdout + result.stderr


def codex_marketplaces() -> str:
    return codex_output(["codex", "plugin", "marketplace", "list"])


def codex_marketplace_roots(listing: str) -> dict[str, str]:
    roots: dict[str, str] = {}
    for line in listing.splitlines():
        columns = line.strip().split(maxsplit=1)
        if len(columns) == 2 and columns[0] != "MARKETPLACE":
            roots[columns[0]] = columns[1]
    return roots


def claude_marketplace_roots() -> dict[str, str]:
    if shutil.which("claude") is None:
        return {}
    raw = run(["claude", "plugin", "marketplace", "list", "--json"], allow_failure=True, quiet=True).stdout
    return claude_marketplace_roots_from_json(raw)


def claude_marketplace_roots_from_json(raw: str) -> dict[str, str]:
    try:
        entries = json.loads(raw)
        return {
            entry["name"]: entry["installLocation"]
            for entry in entries
            if isinstance(entry, dict)
            and isinstance(entry.get("name"), str)
            and isinstance(entry.get("installLocation"), str)
        }
    except (json.JSONDecodeError, TypeError):
        return {}


def claude_marketplace_names() -> set[str]:
    return set(claude_marketplace_roots())


def marketplace_root_is_current(value: str | None) -> bool:
    if not value:
        return False
    try:
        return Path(value).expanduser().resolve() == ROOT
    except (OSError, RuntimeError):
        return False


def migrate_codex_hook_trust(old_id: str, new_id: str) -> bool:
    """Carry hook-trust hashes across a marketplace rename.

    Codex keys trusted hook hashes by `<plugin>@<marketplace>:<file>:<event>`, so a
    marketplace rename silently un-trusts working hooks. The file content is
    unchanged, so the same hashes stay valid: append the new keys rather than
    asking the user to re-approve.
    """
    if not CODEX_CONFIG.is_file():
        return False
    if tomllib is None:
        raise Problem("hook-trust migration requires Python 3.11+ (tomllib)")
    original = CODEX_CONFIG.read_text(encoding="utf-8")
    try:
        parsed = tomllib.loads(original)
    except tomllib.TOMLDecodeError as exc:
        raise Problem(f"~/.codex/config.toml is not valid TOML: {exc}") from exc

    state = parsed.get("hooks", {}).get("state", {})
    carried: list[tuple[str, str]] = []
    for key, value in state.items():
        if not key.startswith(f"{old_id}:"):
            continue
        new_key = f"{new_id}:{key.split(':', 1)[1]}"
        if new_key in state:
            continue
        trusted = value.get("trusted_hash") if isinstance(value, dict) else None
        if trusted:
            carried.append((new_key, str(trusted)))
    if not carried:
        return False

    backup = CODEX_CONFIG.with_suffix(f".toml.bak-{datetime.now(timezone.utc):%Y%m%d%H%M%S}")
    backup.write_text(original, encoding="utf-8")
    block = "\n".join(
        f'\n[hooks.state."{key}"]\ntrusted_hash = "{value}"' for key, value in carried
    )
    CODEX_CONFIG.write_text(f"{original.rstrip()}\n{block}\n", encoding="utf-8")
    try:
        tomllib.loads(CODEX_CONFIG.read_text(encoding="utf-8"))
    except tomllib.TOMLDecodeError as exc:
        CODEX_CONFIG.write_text(original, encoding="utf-8")
        raise Problem(f"hook-trust migration produced invalid TOML, reverted: {exc}") from exc
    print(f"carried {len(carried)} codex hook-trust entr(ies) to {new_id} (backup {backup.name})")
    return True


def repair_memory_guidance_if_configured() -> None:
    if not MEMORY_CONFIG.is_file():
        return
    run(
        [
            sys.executable,
            str(MEMORY_INSTALLER),
            "--reuse-config",
            "--skip-product-install",
            "--skip-upstream-skill-link",
            "--keep-legacy-hooks",
        ]
    )


def memory_guidance_status() -> dict[str, Any]:
    if not MEMORY_CONFIG.is_file():
        return {"configured": False, "ok": True}
    result = run(
        [sys.executable, str(MEMORY_INSTALLER), "--status", "--json"],
        allow_failure=True,
        quiet=True,
    )
    try:
        payload = json.loads(result.stdout)
    except (json.JSONDecodeError, TypeError):
        return {"configured": True, "ok": False, "error": "invalid-status"}
    if not isinstance(payload, dict):
        return {"configured": True, "ok": False, "error": "invalid-status"}
    configured = payload.get("configured")
    ok = payload.get("ok")
    claude = payload.get("claude")
    codex = payload.get("codex")
    valid_states = {
        "claude": {"missing", "stale", "current"},
        "codex": {"missing", "stale", "malformed", "current"},
    }
    status_matches_exit = result.returncode == (0 if ok is True else 1)
    state_is_healthy = claude == "current" and codex == "current"
    if (
        configured is not True
        or not isinstance(ok, bool)
        or any(payload.get(agent) not in states for agent, states in valid_states.items())
        or ok != state_is_healthy
        or not status_matches_exit
    ):
        return {"configured": True, "ok": False, "error": "invalid-status"}
    return {"configured": True, "ok": ok, "claude": claude, "codex": codex}


def cmd_install(args: argparse.Namespace) -> int:
    catalog = load_catalog()
    name = marketplace_name(catalog)
    renames: dict[str, Any] = catalog.get("renames") or {}
    superseded = [old for old, new in renames.items() if new == name and old != name]

    # 1. retire marketplaces this one replaces. Order matters: carry hook trust
    # across the id change, uninstall the plugins that came from the old
    # marketplace (otherwise both copies stay enabled and the same skill loads
    # twice), then drop the marketplace itself.
    for old in superseded:
        for entry in catalog["plugins"]:
            old_id = f"{entry['name']}@{old}"
            migrate_codex_hook_trust(old_id, plugin_id(catalog, entry))
            if shutil.which("codex"):
                run(["codex", "plugin", "remove", old_id], allow_failure=True, quiet=True)
            if shutil.which("claude"):
                run(
                    ["claude", "plugin", "uninstall", old_id, "--scope", args.scope],
                    allow_failure=True,
                    quiet=True,
                )
        if shutil.which("codex"):
            run(["codex", "plugin", "marketplace", "remove", old], allow_failure=True)
        if old in claude_marketplace_names():
            run(["claude", "plugin", "marketplace", "remove", old], allow_failure=True)

    # 1b. retire per-project leftovers that still point inside this repo. A stale
    # marketplace whose manifest was removed makes every `codex plugin` call fail.
    listing = codex_marketplaces()
    for line in listing.splitlines():
        if str(ROOT) not in line:
            continue
        stale = line.strip().lstrip("- ").split("`")
        candidate = stale[1] if len(stale) > 1 else line.split()[0]
        if candidate and candidate != name:
            run(["codex", "plugin", "marketplace", "remove", candidate], allow_failure=True)

    # 2. register this marketplace in both agents.
    if shutil.which("codex") is None:
        print("codex not on PATH — skipping Codex")
    else:
        codex_roots = codex_marketplace_roots(codex_marketplaces())
        if (
            getattr(args, "force", False)
            and name in codex_roots
            and not marketplace_root_is_current(codex_roots[name])
        ):
            run(["codex", "plugin", "marketplace", "remove", name], allow_failure=True)
            codex_roots = codex_marketplace_roots(codex_marketplaces())
        if name not in codex_roots:
            run(
                ["codex", "plugin", "marketplace", "add", str(ROOT), "--json"],
                allow_failure=True,
            )
        for entry in catalog["plugins"]:
            pid = plugin_id(catalog, entry)
            if getattr(args, "force", False):
                run(["codex", "plugin", "remove", pid], allow_failure=True, quiet=True)
            run(["codex", "plugin", "add", pid, "--json"], allow_failure=True)

    if shutil.which("claude") is None:
        print("claude not on PATH — skipping Claude Code")
    elif not claude_marketplace_needed(catalog):
        print("claude: every plugin is delivered by claude-core — no marketplace needed")
    else:
        claude_roots = claude_marketplace_roots()
        if (
            getattr(args, "force", False)
            and name in claude_roots
            and not marketplace_root_is_current(claude_roots[name])
        ):
            run(
                ["claude", "plugin", "marketplace", "remove", name, "--scope", args.scope],
                allow_failure=True,
            )
            claude_roots = claude_marketplace_roots()
        if name not in claude_roots:
            run(
                ["claude", "plugin", "marketplace", "add", str(ROOT), "--scope", args.scope],
                allow_failure=True,
            )
        else:
            # This marketplace is a local directory, so a version bump in this repo is only
            # visible to Claude Code after the marketplace is re-read.
            run(["claude", "plugin", "marketplace", "update", name], allow_failure=True)
        for entry in catalog["plugins"]:
            if delivered_by_claude_core(entry):
                continue
            pid = plugin_id(catalog, entry)
            # Versions are pinned for local development, so neither `install` (a no-op when
            # already present) nor `update` (a no-op when the version is unchanged) will pick
            # up edited files, and the CLI has no --force. Uninstalling first is the only way
            # to make Claude Code re-copy the directory. --keep-data preserves plugin state.
            if getattr(args, "force", False):
                run(
                    ["claude", "plugin", "uninstall", pid, "--scope", args.scope, "--yes", "--keep-data"],
                    allow_failure=True,
                )
            run(["claude", "plugin", "install", pid, "--scope", args.scope], allow_failure=True)
            # Still attempt an update: harmless when pinned, and it covers the case where
            # someone does bump a version without --force.
            run(["claude", "plugin", "update", pid, "--scope", args.scope], allow_failure=True)
            if getattr(args, "force", False):
                # A fresh install can land disabled; enablement is what makes it load.
                run(["claude", "plugin", "enable", pid, "--scope", args.scope], allow_failure=True)

    # Codex rewrites config.toml while adding marketplaces/plugins, so re-assert
    # the carried hook trust once the dust settles.
    for old in superseded:
        for entry in catalog["plugins"]:
            migrate_codex_hook_trust(f"{entry['name']}@{old}", plugin_id(catalog, entry))

    repair_memory_guidance_if_configured()

    # Every step above tolerates failure so one bad plugin cannot abort the rest — so the
    # only trustworthy report is the postcondition: is this repo's version actually live?
    rc = cmd_status(args)
    if rc:
        print(f"\n{name}: install did NOT fully apply — see the marked rows above")
        return rc
    print(f"\n{name}: {len(catalog['plugins'])} plugin(s) wired into both agents")
    print("start a new Claude Code / Codex thread to load them")
    return 0


def cmd_uninstall(args: argparse.Namespace) -> int:
    catalog = load_catalog()
    name = marketplace_name(catalog)
    for entry in catalog["plugins"]:
        pid = plugin_id(catalog, entry)
        if shutil.which("codex"):
            run(["codex", "plugin", "remove", pid], allow_failure=True)
        if shutil.which("claude") and not delivered_by_claude_core(entry):
            run(["claude", "plugin", "uninstall", pid, "--scope", args.scope], allow_failure=True)
    if shutil.which("codex"):
        run(["codex", "plugin", "marketplace", "remove", name], allow_failure=True)
    if shutil.which("claude") and claude_marketplace_needed(catalog):
        run(["claude", "plugin", "marketplace", "remove", name], allow_failure=True)
    print(f"{name} removed from both agents (files in this repo are untouched)")
    return 0


# Runtime droppings that live inside a cache copy or a checkout but are not the plugin.
DIGEST_IGNORE = {".orphaned_at", ".in_use", "__pycache__", ".DS_Store", ".git", "node_modules"}


def tree_digest(root: Path) -> str:
    """Content fingerprint of a plugin directory: relative paths plus bytes.

    With versions pinned, a version comparison can no longer tell whether the live cache
    matches this checkout — only content can. Returns "" when the directory is missing.
    """
    if not root.is_dir():
        return ""
    digest = hashlib.sha256()
    for path in sorted(root.rglob("*")):
        if DIGEST_IGNORE & set(path.relative_to(root).parts):
            continue
        if not path.is_file():
            continue
        digest.update(str(path.relative_to(root)).encode())
        digest.update(path.read_bytes())
    return digest.hexdigest()


def claude_install_paths() -> dict[str, str]:
    """Where Claude Code keeps each plugin's live copy, per its own install record."""
    path = Path.home() / ".claude" / "plugins" / "installed_plugins.json"
    if not path.is_file():
        return {}
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return {}
    return {
        pid: str(records[0].get("installPath") or "")
        for pid, records in (data.get("plugins") or {}).items()
        if isinstance(records, list) and records
    }


def claude_installed_versions() -> dict[str, str]:
    """What Claude Code actually serves: the installed cache copy, not this repo's manifest.

    Without this, `status` reports the version it just rendered and a failed upgrade looks
    like a successful one.
    """
    path = Path.home() / ".claude" / "plugins" / "installed_plugins.json"
    if not path.is_file():
        return {}
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return {}
    live: dict[str, str] = {}
    for pid, records in (data.get("plugins") or {}).items():
        if isinstance(records, list) and records:
            live[pid] = str(records[0].get("version") or "?")
    return live


def codex_plugin_states(listing: str, marketplace: str) -> dict[str, dict[str, Any]]:
    """Parse one complete Codex marketplace table without exposing its paths."""
    active = False
    columns: tuple[int, int, int] | None = None
    states: dict[str, dict[str, Any]] = {}
    for line in listing.splitlines():
        section = re.fullmatch(r"Marketplace `([^`]+)`", line.strip())
        if section:
            active = section.group(1) == marketplace
            columns = None
            continue
        if not active:
            continue
        if line.lstrip().startswith("PLUGIN") and all(
            label in line for label in ("STATUS", "VERSION")
        ):
            source_label = next(
                (label for label in ("SOURCE", "PATH") if label in line),
                None,
            )
            if source_label is None:
                continue
            columns = (line.index("STATUS"), line.index("VERSION"), line.index(source_label))
            continue
        if columns is None or not line.strip():
            continue
        status_start, version_start, path_start = columns
        plugin_id_value = line[:status_start].strip()
        if not plugin_id_value:
            continue
        status = line[status_start:version_start].strip()
        states[plugin_id_value] = {
            "installed": status.startswith("installed"),
            "enabled": status == "installed, enabled",
            "version": line[version_start:path_start].strip(),
            "path": line[path_start:].strip(),
        }
    return states


def claude_plugin_states(raw: str) -> dict[str, dict[str, Any]]:
    """Parse Claude's bounded JSON plugin projection."""
    try:
        entries = json.loads(raw)
    except (json.JSONDecodeError, TypeError):
        return {}
    if not isinstance(entries, list):
        return {}
    states: dict[str, dict[str, Any]] = {}
    for entry in entries:
        if not isinstance(entry, dict) or not isinstance(entry.get("id"), str):
            continue
        states[entry["id"]] = {
            "installed": True,
            "enabled": entry.get("enabled") is True,
            "version": entry.get("version") if isinstance(entry.get("version"), str) else "",
            "path": entry.get("installPath") if isinstance(entry.get("installPath"), str) else "",
        }
    return states


def plugin_live_state(
    *,
    available: bool,
    marketplace_current: bool,
    state: dict[str, Any] | None,
    source: Path,
) -> str:
    """Return one bounded product/plugin postcondition label."""
    if not available:
        return "CLI MISSING"
    if not marketplace_current:
        return "MARKETPLACE"
    if not state or state.get("installed") is not True:
        return "MISSING"
    if state.get("enabled") is not True:
        return "DISABLED"
    live_path = state.get("path")
    source_digest = tree_digest(source)
    if (
        not isinstance(live_path, str)
        or not live_path
        or not source_digest
        or tree_digest(Path(live_path)) != source_digest
    ):
        return "STALE"
    return "ok"


def cmd_status(args: argparse.Namespace) -> int:
    _ = args
    catalog = load_catalog()
    name = marketplace_name(catalog)
    print(f"\nmarketplace: {name}")

    codex_available = shutil.which("codex") is not None
    codex_marketplace_ok = False
    codex_states: dict[str, dict[str, Any]] = {}
    if codex_available:
        marketplace_result = run(
            ["codex", "plugin", "marketplace", "list"],
            allow_failure=True,
            quiet=True,
        )
        plugin_result = run(
            ["codex", "plugin", "list"], allow_failure=True, quiet=True
        )
        marketplace_listing = marketplace_result.stdout + marketplace_result.stderr
        plugin_listing = plugin_result.stdout + plugin_result.stderr
        codex_marketplace_ok = (
            marketplace_result.returncode == 0
            and marketplace_root_is_current(
                codex_marketplace_roots(marketplace_listing).get(name)
            )
        )
        if plugin_result.returncode == 0:
            codex_states = codex_plugin_states(plugin_listing, name)

    claude_available = shutil.which("claude") is not None
    claude_marketplace_ok = False
    claude_states: dict[str, dict[str, Any]] = {}
    if claude_available:
        marketplace_result = run(
            ["claude", "plugin", "marketplace", "list", "--json"],
            allow_failure=True,
            quiet=True,
        )
        plugin_result = run(
            ["claude", "plugin", "list", "--json"],
            allow_failure=True,
            quiet=True,
        )
        claude_marketplace_ok = (
            marketplace_result.returncode == 0
            and marketplace_root_is_current(
                claude_marketplace_roots_from_json(marketplace_result.stdout).get(name)
            )
        )
        if plugin_result.returncode == 0:
            claude_states = claude_plugin_states(plugin_result.stdout)

    claude_needed = claude_marketplace_needed(catalog)

    def marketplace_label(available: bool, current: bool) -> str:
        if not available:
            return "CLI MISSING"
        return "current" if current else "MISSING OR STALE"

    print(f"codex:  marketplace {marketplace_label(codex_available, codex_marketplace_ok)}")
    if claude_needed:
        print(f"claude: marketplace {marketplace_label(claude_available, claude_marketplace_ok)}")
    else:
        print("claude: marketplace not needed (claude-core delivers every plugin)")
    print(f"\n{'plugin':<20} {'repo':<10} {'codex':<12} claude")
    unhealthy = not (
        codex_available
        and claude_available
        and codex_marketplace_ok
        and (claude_marketplace_ok or not claude_needed)
    )
    for entry in catalog["plugins"]:
        pid = plugin_id(catalog, entry)
        repo_version = plugin_version(entry)
        codex_state = plugin_live_state(
            available=codex_available,
            marketplace_current=codex_marketplace_ok,
            state=codex_states.get(pid),
            source=plugin_dir(entry),
        )
        if delivered_by_claude_core(entry):
            claude_state = claude_core_state(plugin_dir(entry))
        else:
            claude_state = plugin_live_state(
                available=claude_available,
                marketplace_current=claude_marketplace_ok,
                state=claude_states.get(pid),
                source=plugin_dir(entry),
            )
        unhealthy = unhealthy or codex_state != "ok" or claude_state not in ("ok", "claude-core")
        print(
            f"{entry['name']:<20} {repo_version:<10} {codex_state:<12} {claude_state}"
        )

    guidance = memory_guidance_status()
    if guidance.get("error") == "invalid-status":
        print("guidance: invalid status")
    elif not guidance["configured"]:
        print("guidance: not configured")
    else:
        print(f"guidance: Claude {guidance['claude']}; Codex {guidance['codex']}")

    return 1 if unhealthy or not guidance["ok"] else 0


def main() -> int:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    sub = parser.add_subparsers(dest="command", required=True)

    p = sub.add_parser("sync", help="render manifests from plugins.json")
    p.add_argument("--check", action="store_true", help="fail on drift instead of writing")
    p.set_defaults(func=cmd_sync)

    p = sub.add_parser("check", help="validate the catalog, manifests and plugins")
    p.add_argument("--fast", action="store_true", help="skip the per-project check suites")
    p.set_defaults(func=cmd_check)

    p = sub.add_parser("status", help="what each agent has registered")
    p.set_defaults(func=cmd_status)

    p = sub.add_parser("install", help="register + install every plugin in both agents")
    p.add_argument("--scope", default="user", choices=["user", "project", "local"])
    p.add_argument(
        "--force",
        action="store_true",
        help="reinstall from scratch so edited files land even with the version unchanged",
    )
    p.set_defaults(func=cmd_install)

    p = sub.add_parser("uninstall", help="remove the marketplace and plugins from both agents")
    p.add_argument("--scope", default="user", choices=["user", "project", "local"])
    p.set_defaults(func=cmd_uninstall)

    args = parser.parse_args()
    return int(args.func(args))


if __name__ == "__main__":
    ensure_modern_python()
    try:
        raise SystemExit(main())
    except Problem as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        raise SystemExit(1)
