#!/usr/bin/env python3
"""Render Claude agents from the catalog and prompt bodies."""

from __future__ import annotations

import argparse
import json
import textwrap
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1] / "agents"
CATALOG = ROOT / "agents.json"
CLAUDE_AGENTS = ROOT / "rendered"
GENERATED = "GENERATED by claude-core/scripts/render.py from agents.json and prompts/ — do not edit."


class Problem(RuntimeError):
    pass


def load_catalog() -> list[dict[str, Any]]:
    try:
        payload = json.loads(CATALOG.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise Problem(f"agents.json: {exc}") from exc
    agents = payload.get("agents")
    if not isinstance(agents, list) or not agents:
        raise Problem("agents.json: agents must be a non-empty array")

    ids: set[str] = set()
    claude_names: set[str] = set()
    for agent in agents:
        agent_id = agent.get("id")
        if not isinstance(agent_id, str) or not agent_id:
            raise Problem("agents.json: every agent needs an id")
        if agent_id in ids:
            raise Problem(f"agents.json: duplicate id {agent_id}")
        ids.add(agent_id)
        prompt = ROOT / str(agent.get("prompt", ""))
        if not prompt.is_file():
            raise Problem(f"{agent_id}: missing prompt {prompt.relative_to(ROOT)}")
        if not agent.get("description"):
            raise Problem(f"{agent_id}: description is required")
        claude = agent.get("claude")
        if not isinstance(claude, dict) or not claude:
            raise Problem(f"{agent_id}: claude settings are required")
        claude_name = claude.get("name", agent_id)
        if not isinstance(claude_name, str) or not claude_name:
            raise Problem(f"{agent_id}: claude.name must be a non-empty string")
        if claude_name in claude_names:
            raise Problem(f"agents.json: duplicate Claude name {claude_name}")
        claude_names.add(claude_name)
    return agents


def yaml_folded(value: str, indent: int = 2) -> str:
    width = 88 - indent
    return "\n".join(" " * indent + line for line in textwrap.wrap(value, width=width))


def render_claude(agent: dict[str, Any], prompt: str) -> str:
    config = agent["claude"]
    claude_name = config.get("name", agent["id"])
    frontmatter = [
        "---",
        f"name: {claude_name}",
        "description: >",
        yaml_folded(str(agent["description"])),
        f"model: {config['model']}",
        f"effort: {config['effort']}",
    ]
    for key in ("maxTurns", "permissionMode", "memory"):
        if config.get(key) is not None:
            frontmatter.append(f"{key}: {config[key]}")
    for key in ("tools", "disallowedTools"):
        if config.get(key):
            frontmatter.append(f"{key}: {', '.join(config[key])}")
    frontmatter.extend(["---", "", f"<!-- {GENERATED} -->", ""])
    return "\n".join(frontmatter) + prompt.rstrip() + "\n"


def expected_files() -> dict[Path, str]:
    rendered: dict[Path, str] = {}
    for agent in load_catalog():
        prompt = (ROOT / agent["prompt"]).read_text(encoding="utf-8")
        claude_name = agent["claude"].get("name", agent["id"])
        rendered[CLAUDE_AGENTS / f"{claude_name}.md"] = render_claude(agent, prompt)
    return rendered


def render(check: bool = False) -> list[Path]:
    expected = expected_files()
    changed: list[Path] = []
    for path, content in expected.items():
        current = path.read_text(encoding="utf-8") if path.is_file() else None
        if current == content:
            continue
        changed.append(path)
        if not check:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")

    expected_paths = set(expected)
    if CLAUDE_AGENTS.is_dir():
        for path in CLAUDE_AGENTS.glob("*.md"):
            if path in expected_paths:
                continue
            changed.append(path)
            if not check:
                path.unlink()
    return changed


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail on drift without writing")
    args = parser.parse_args()
    changed = render(check=args.check)
    for path in changed:
        print(("would update " if args.check else "updated ") + str(path.relative_to(ROOT)))
    if args.check and changed:
        print("run: python3 scripts/render.py")
        return 1
    if not changed:
        print("all rendered agent files match the catalog")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except Problem as exc:
        print(f"ERROR: {exc}")
        raise SystemExit(1)
